name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build APK (debug)
        working-directory: android_app
        run: ./gradlew --no-daemon assembleDebug

      - name: Rename APK for release asset
        working-directory: android_app
        run: |
          mkdir -p app/build/outputs/apk/release_asset
          cp app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/release_asset/Score_King-${{ github.ref_name }}-android-debug.apk

      - name: Create GitHub Release and upload APK
        uses: softprops/action-gh-release@v2
        with:
          name: Score King ${{ github.ref_name }}
          body_path: RELEASE_NOTES.md
          files: |
            android_app/app/build/outputs/apk/release_asset/Score_King-${{ github.ref_name }}-android-debug.apk
          draft: false
          prerelease: false


